Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: crypto-config/ordererOrganizations/sdms.gov.in/msp

  - &PoliceOrg
    Name: PoliceMSP
    ID: PoliceMSP
    MSPDir: crypto-config/peerOrganizations/police.sdms.gov.in/msp

  - &ForensicsOrg
    Name: ForensicsMSP
    ID: ForensicsMSP
    MSPDir: crypto-config/peerOrganizations/forensics.sdms.gov.in/msp

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_0: true

Application: &ApplicationDefaults
  Organizations:
  Capabilities:
    <<: *ApplicationCapabilities

Profiles:
  TwoOrgsOrdererGenesis:
    <<: *ChannelDefaults
    Orderer:
      OrdererType: etcdraft
      Addresses:
        - orderer.sdms.gov.in:7050
      Organizations:
        - *OrdererOrg
      Capabilities: *OrdererCapabilities
    Consortiums:
      SampleConsortium:
        Organizations:
          - *PoliceOrg
          - *ForensicsOrg

  DocHashChannel:
    Consortium: SampleConsortium
    <<: *ChannelDefaults
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *PoliceOrg
        - *ForensicsOrg
      Capabilities: *ApplicationCapabilities

  AccessChannel:
    Consortium: SampleConsortium
    <<: *ChannelDefaults
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *PoliceOrg
        - *ForensicsOrg
      Capabilities: *ApplicationCapabilities
