from enum import Enum

class UserRole(str, Enum):
    INVESTIGATOR = "INVESTIGATOR"
    FORENSIC_ANALYST = "FORENSIC_ANALYST"
    LEGAL_OFFICER = "LEGAL_OFFICER"
    SUPERVISOR = "SUPERVISOR"
    LAWYER = "LAWYER"
    ADMIN = "ADMIN"

class ClassificationLevel(str, Enum):
    RESTRICTED = "RESTRICTED"
    CONFIDENTIAL = "CONFIDENTIAL"
    SECRET = "SECRET"

class DocumentType(str, Enum):
    FIR = "FIR"
    CHARGESHEET = "CHARGESHEET"
    FORENSIC_REPORT = "FORENSIC_REPORT"
    COURT_ORDER = "COURT_ORDER"
    CASE_DIARY = "CASE_DIARY"
    SEIZURE_MEMO = "SEIZURE_MEMO"
    WITNESS_STATEMENT = "WITNESS_STATEMENT"
    EVIDENCE_PHOTO = "EVIDENCE_PHOTO"

class DocumentStatus(str, Enum):
    ACTIVE = "ACTIVE"
    QUARANTINED = "QUARANTINED"
    SHREDDED = "SHREDDED"

class AuditAction(str, Enum):
    LOGIN_OK = "LOGIN_OK"
    LOGIN_FAIL = "LOGIN_FAIL"
    MFA_FAIL = "MFA_FAIL"
    UPLOAD_OK = "UPLOAD_OK"
    UPLOAD_MALWARE = "UPLOAD_MALWARE"
    QUERY = "QUERY"
    QUERY_DENIED = "QUERY_DENIED"
    QUERY_ANSWERED = "QUERY_ANSWERED"
    RETRIEVE = "RETRIEVE"
    DOC_VIEW = "DOC_VIEW"
    DOC_DOWNLOAD = "DOC_DOWNLOAD"
    VERIFY_OK = "VERIFY_OK"
    VERIFY_FAIL = "VERIFY_FAIL"
    TAMPER_ALERT = "TAMPER_ALERT"
    ROLE_CHANGE = "ROLE_CHANGE"
    CASE_ASSIGN = "CASE_ASSIGN"
    CASE_REVOKE = "CASE_REVOKE"
    CERT_ISSUED = "CERT_ISSUED"
    SHRED = "SHRED"

class AuditOutcome(str, Enum):
    ALLOW = "ALLOW"
    DENY = "DENY"
    ERROR = "ERROR"
